Repository B4-Group/swe_b4, pull requests merged in 2022-11, with the labels that each got.

#5 Added Unity Project & Unity gitignore
  .gitignore
  Assets/Scenes.meta
  Assets/Scenes/SampleScene.unity
  Assets/Scenes/SampleScene.unity.meta
  Assets/Settings.meta
  Assets/Settings/Lit2DSceneTemplate.scenetemplate
  Assets/Settings/Lit2DSceneTemplate.scenetemplate.meta
  Assets/Settings/Renderer2D.asset
  Assets/Settings/Renderer2D.asset.meta
  Assets/Settings/Scenes.meta
  Assets/Settings/Scenes/URP2DSceneTemplate.unity
  Assets/Settings/Scenes/URP2DSceneTemplate.unity.meta
  Assets/Settings/UniversalRP.asset
  Assets/Settings/UniversalRP.asset.meta
  Assets/UniversalRenderPipelineGlobalSettings.asset
  Assets/UniversalRenderPipelineGlobalSettings.asset.meta
  Packages/manifest.json
  Packages/packages-lock.json
  ProjectSettings/AudioManager.asset
  ProjectSettings/ClusterInputManager.asset
  ProjectSettings/DynamicsManager.asset
  ProjectSettings/EditorBuildSettings.asset
  ProjectSettings/EditorSettings.asset
  ProjectSettings/GraphicsSettings.asset
  ProjectSettings/InputManager.asset
  ProjectSettings/MemorySettings.asset
  ProjectSettings/NavMeshAreas.asset
  ProjectSettings/NetworkManager.asset
  ProjectSettings/PackageManagerSettings.asset
  ProjectSettings/Physics2DSettings.asset
  ProjectSettings/PresetManager.asset
  ProjectSettings/ProjectSettings.asset
  ProjectSettings/ProjectVersion.txt
  ProjectSettings/QualitySettings.asset
  ProjectSettings/TagManager.asset
  ProjectSettings/TimeManager.asset
  ProjectSettings/URPProjectSettings.asset
  ProjectSettings/UnityConnectSettings.asset
  ProjectSettings/VFXManager.asset
  ProjectSettings/VersionControlSettings.asset
  ProjectSettings/XRSettings.asset
  ProjectSettings/boot.config
Labels: enhancement

#8 Update .gitignore
  .gitignore
Labels: Bugfix

#9 Update .gitignore
  .gitignore
Labels: enhancement

#11 WallCollider, Layers und ThrowAnimation
  Assets/Characters/Persian Warrior.controller
  Assets/Characters/Persian Warrior.prefab
  Assets/PyramidQuest.inputactions
  Assets/PyramidQuest.inputactions.meta
  Assets/Scenes/SampleScene.unity
  Assets/Scripts/Interact.cs
  Assets/Scripts/Interact.cs.meta
  Assets/Scripts/PlayerController.cs
  Assets/Scripts/PlayerController.cs.meta
  Assets/Scripts/PuzzelInteraction.cs
  Assets/Scripts/PuzzelInteraction.cs.meta
  Assets/Tiles/DungeonSet.prefab
  Packages/manifest.json
  Packages/packages-lock.json
  ProjectSettings/ProjectSettings.asset
  ProjectSettings/TagManager.asset
  ProjectSettings/TimelineSettings.asset
Labels: enhancement

#25 Fixed player controller being in gitignore
  .gitignore
  Assets/Characters/Player/Persian Warrior.prefab
  Assets/Characters/Player/PlayerController.controller
  Assets/Characters/Player/PlayerController.controller.meta
  Assets/Scenes/SampleScene.unity
Labels: enhancement, Bugfix

#26 Bug Fixes for Pausenmenu and Prevent Shooting when game is paused
  Assets/Scenes/SampleScene.unity
  Assets/Scripts/Pausenmenu.cs
  Assets/Scripts/Shooting.cs
Labels: Bugfix

#28 Added AudioManager and footsteps
  Assets/Audio.meta
  Assets/Audio/click.mp3
  Assets/Audio/click.mp3.meta
  Assets/Audio/step.mp3
  Assets/Audio/step.mp3.meta
  Assets/Prefabs/AudioManager.prefab
  Assets/Prefabs/AudioManager.prefab.meta
  Assets/Scenes/Levelauswahl.unity
  Assets/Scenes/Levels/Level1.unity
  Assets/Scenes/Levels/Level2.unity
  Assets/Scenes/MainMenu.unity
  Assets/Scripts/AudioManager.cs
  Assets/Scripts/AudioManager.cs.meta
  Assets/Scripts/MainMenu.cs
  Assets/Scripts/Pausenmenu.cs
  Assets/Scripts/PlayerMovement.cs
  Assets/Scripts/Sound.cs
  Assets/Scripts/Sound.cs.meta
  ProjectSettings/EditorBuildSettings.asset
Labels: enhancement, Bugfix

#30 HealthSystem
  Assets/Characters/Player/Persian Warrior.prefab
  Assets/Characters/Player/PlayerController.controller
  Assets/Scenes/SampleScene.unity
  Assets/Scripts/PlayerHealth.cs
  Assets/UI/UI Screens/HealthBar.uxml
  Assets/UI/UI Screens/HealthBar.uxml.meta
  Assets/UI/UI Screens/gameUI.uxml
  Assets/UI/UI Toolkit/Game Icon/Cartoon RPG UI_Game Icon - Empty Heart.png
  Assets/UI/UI Toolkit/Game Icon/Cartoon RPG UI_Game Icon - Empty Heart.png.meta
Labels: enhancement

#32 Player health, light Adjustments & Error fixes
  Assets/Characters/Player/Persian Warrior.prefab
  Assets/Scenes/Levels/Level1.unity
  Assets/Scripts/GridShadowCastersGenerator.cs
  Assets/Scripts/GridShadowCastersGenerator.cs.meta
  Assets/Scripts/PlayerHealth.cs
  Assets/UI Toolkit.meta
  Assets/UI Toolkit/UnityThemes.meta
  Assets/UI Toolkit/UnityThemes/UnityDefaultRuntimeTheme.tss
  Assets/UI Toolkit/UnityThemes/UnityDefaultRuntimeTheme.tss.meta
  ProjectSettings/ProjectSettings.asset
Labels: enhancement, Bugfix

#35 Quizz popup + Simonsays
  Assets/Popup Ui.meta
  Assets/Popup Ui/Prefabs.meta
  Assets/Popup Ui/Prefabs/Popup.prefab
  Assets/Popup Ui/Prefabs/Popup.prefab.meta
  Assets/Popup Ui/Scripts.meta
  Assets/Popup Ui/Scripts/PopupUi.cs
  Assets/Popup Ui/Scripts/PopupUi.cs.meta
  Assets/Popup Ui/Scripts/SimonsaysScript.cs
  Assets/Popup Ui/Scripts/SimonsaysScript.cs.meta
  Assets/Scenes/SampleScene.unity
Labels: enhancement

#36 PopUi does start on game start fix
  Assets/Popup Ui/Scripts/PopupUi.cs
Labels: Bugfix

#39 Added Hieroglyphen Rechner
  Assets/Popup Ui/Prefabs/Popup.prefab
  Assets/Popup Ui/Scripts/CalculatorScript.cs
  Assets/Popup Ui/Scripts/CalculatorScript.cs.meta
  Assets/Popup Ui/Scripts/PopupUi.cs
Labels: enhancement

#40 Added menu music
  Assets/Audio/Music/belly-dance-middle-east-arabic-oriental-ethnic-118609.mp3
  Assets/Audio/Music/belly-dance-middle-east-arabic-oriental-ethnic-118609.mp3.meta
  Assets/Prefabs/AudioManager.prefab
  Assets/Scripts/UI/LevelauswahlScript.cs
  Assets/Scripts/UI/MainMenu.cs
Labels: enhancement

#43 Sounds updated (With merge conflict)
  Assets/Audio/DM-CGS-21.wav
  Assets/Audio/DM-CGS-21.wav.meta
  Assets/Audio/exit.mp3
  Assets/Audio/exit.mp3.meta
  Assets/Audio/lose.mp3
  Assets/Audio/lose.mp3.meta
  Assets/Audio/mummy1.mp3
  Assets/Audio/mummy1.mp3.meta
  Assets/Audio/mummy2.mp3
  Assets/Audio/mummy2.mp3.meta
  Assets/Audio/mummy3.mp3
  Assets/Audio/mummy3.mp3.meta
  Assets/Audio/mummy_death.mp3
  Assets/Audio/mummy_death.mp3.meta
  Assets/Audio/select.mp3
  Assets/Audio/select.mp3.meta
  Assets/Audio/star_collected.mp3
  Assets/Audio/star_collected.mp3.meta
  Assets/Audio/start.mp3
  Assets/Audio/start.mp3.meta
  Assets/Audio/throw.mp3
  Assets/Audio/throw.mp3.meta
  Assets/Audio/win.mp3
  Assets/Audio/win.mp3.meta
  Assets/Scenes/MainMenu.unity
  Assets/Scripts/Enemy/EnemyGFX.cs
  Assets/Scripts/Enemy/EnemyHealth.cs
  Assets/Scripts/Level/Stars.cs
  Assets/Scripts/Player/Shooting.cs
  Assets/Scripts/UI/LevelauswahlScript.cs
  Assets/Scripts/UI/MainMenu.cs
Labels: enhancement
