Repository B4-Group/swe_b4, pull requests merged in 2023-01, with the labels that each got.

#86 Fixed calculator math problem and simonsays counter and timer reset
  Assets/Prefabs/Puzzle/PuzzlePopup.prefab
  Assets/Scripts/Puzzle/SimonsaysScript.cs
Labels: Bugfix

#94 trapsystem/healthsystem
  Assets/SaveData.json.meta
  Assets/Scripts/Player/PlayerHealth.cs
  Assets/Scripts/Trap.meta
  Assets/Scripts/Trap/Trap.cs
  Assets/Scripts/Trap/Trap.cs.meta
  Assets/Scripts/UI/Pausenmenu.cs
  ProjectSettings/TagManager.asset
Labels: enhancement, Bugfix

#97 Fix for broken script
  Assets/Scenes/Levels/Tutorial.unity
  Assets/Scripts/Shadow/GridShadowCastersGenerator.cs
  Assets/Scripts/Shadow/GridShadowCastersGenerator.cs.meta
Labels: Bugfix

#99 Updated Audio Slider + fixed Audio related bugs
  Assets/Prefabs/AudioManager.prefab
  Assets/SaveData.json
  Assets/Scenes/MainMenu.unity
  Assets/Scripts/Audio/AudioManager.cs
  Assets/Scripts/Audio/SliderEvents.cs
  Assets/Scripts/Level/Torch.cs
  Assets/Scripts/UI/LevelauswahlScript.cs
  Assets/Scripts/UI/Pausenmenu.cs
Labels: enhancement, Bugfix

#107 Changed Attack Key to Space
  Assets/Characters/Player/Player.prefab
  Assets/PyramidQuest.inputactions
  Assets/Resources/Leertaste.png
  Assets/Resources/Leertaste.png.meta
  Assets/Resources/linksKlick.png
  Assets/SaveData.json
  Assets/Scenes/Levels/Tempel des Todes.unity
  Assets/Scenes/Levels/Tutorial.unity
  Assets/Scripts/Player/PlayerHealth.cs
Labels: enhancement, Bugfix

#109 Hint Dialogue improvements
  Assets/Prefabs/Puzzle/HintUI.uxml
  Assets/Prefabs/Puzzle/PuzzlePopup.prefab
  Assets/Scripts/Puzzle/HintDialogue.cs
Labels: Bugfix

#122 Fixed Save System
  Assets/Scripts/Level/LevelController.cs
Labels: Bugfix

#124 Updated Main Menu text to german
  Assets/UI/UI Screens/mainMenu.uxml
  Assets/UI/UI Toolkit/Buttons/Text/Button Text - Spielen.png
  Assets/UI/UI Toolkit/Buttons/Text/Button Text - Spielen.png.meta
  Assets/UI/UI Toolkit/Buttons/Text/Button Text - schliessen.png
  Assets/UI/UI Toolkit/Buttons/Text/Button Text - schliessen.png.meta
Labels: Bugfix, Design

#123 Adjusted Audio System + Bugfix
  Assets/Prefabs/AudioManager.prefab
  Assets/SaveData.json
  Assets/Scripts/Level/LevelController.cs
  Assets/Scripts/Level/Torch.cs
  Assets/Scripts/Puzzle/SimonsaysScript.cs
  Assets/Scripts/UI/Pausenmenu.cs
Labels: enhancement, Bugfix

#125 Fixed Level1 Void
  Assets/Scenes/Levels/Tempel des Todes.unity
Labels: bug, Design

#126 Puzzle UI Close Btn & Fixed PuzzleDoor bug
  Assets/Prefabs/Puzzle/PuzzlePopup.prefab
  Assets/Scripts/Interfaces/Interactable.cs
  Assets/Scripts/Level/DoorController.cs
  Assets/Scripts/Puzzle/PuzzelController.cs
  Assets/UI/UI Toolkit/Buttons/Text/Button Text - X.png
  Assets/UI/UI Toolkit/Buttons/Text/Button Text - X.png.meta
Labels: Bugfix, Design

#128 Fixed PuzzlePopup contrast
  Assets/Prefabs/Puzzle/PuzzlePopup.prefab
Labels: Bugfix, Design

#129 Fixed overlapping images in simon says
  Assets/Prefabs/Puzzle/PuzzlePopup.prefab
Labels: Bugfix, Design

#131 Fixed Audio not stopping on Tutorial load
  Assets/Scripts/UI/LevelauswahlScript.cs
Labels: Bugfix

#133 UI Buttons ;/
  Assets/UI/UI Screens/gameUI.uxml
Labels: Bugfix, Design

#140 Fixed Door events being connected
  Assets/Prefabs/Puzzle/HintUI.uxml
  Assets/Prefabs/Puzzle/PuzzlePopup.prefab
  Assets/SaveData.json
  Assets/Scenes/Levels/Tempel des Todes.unity
  Assets/Scripts/Puzzle/InformationPanelScript.cs
  Assets/Scripts/Puzzle/PuzzelController.cs
  Assets/Scripts/Puzzle/PuzzleUiController.cs
Labels: Bugfix

#146 Fixed Highscore just being the last score
  Assets/Scripts/Level/LevelController.cs
Labels: Bugfix

#145 Updated Readme
  README.md
Labels: documentation

#148 Update README.md
  README.md
Labels: documentation

#149 Readme update
  README.md
Labels: documentation

#151 Fixed Pausenmenü bein accessible while dead
  Assets/Scripts/Player/PlayerHealth.cs
  Assets/Scripts/UI/Pausenmenu.cs
Labels: Bugfix

#153 Fixed #152
  Assets/Scripts/Player/PlayerHealth.cs
Labels: Bugfix

#155 Fixed #154
  Assets/Scripts/Level/GameCompleted.cs
  Assets/Scripts/Level/LevelController.cs
Labels: Bugfix
